"use client";

import { ChangeEvent, useCallback, useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Download, Eye, FileUp, Loader2, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { toast, Toaster } from "sonner";

type Supplier = {
  id: number; supplierCode: string; name: string; contactPerson: string | null; phone: string | null; whatsapp: string | null;
  email: string | null; address: string | null; city: string | null; country: string | null; taxNumber: string | null;
  status: "ACTIVE" | "INACTIVE"; notes: string | null; items: { id: number; name: string; sku: string; currentStock?: string; unit?: string }[];
};
type Form = Record<string, string>;
const emptyForm = (): Form => ({ name: "", contactPerson: "", phone: "", whatsapp: "", email: "", address: "", city: "", country: "", taxNumber: "", status: "ACTIVE", notes: "" });
const fields = [["name", "Company name"], ["contactPerson", "Contact person"], ["phone", "Phone number"], ["whatsapp", "WhatsApp"], ["email", "Email"], ["address", "Address"], ["city", "City"], ["country", "Country"], ["taxNumber", "Tax number (optional)"]];

export default function SuppliersPage() {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [page, setPage] = useState(1); const [pageCount, setPageCount] = useState(1); const [total, setTotal] = useState(0);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [sort, setSort] = useState("name"); const [loading, setLoading] = useState(true);
  const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Supplier | null>(null); const [form, setForm] = useState<Form>(emptyForm()); const [selected, setSelected] = useState<Supplier | null>(null); const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ page: String(page), pageSize: "10", sort });
      if (search.trim()) params.set("search", search.trim()); if (status !== "ALL") params.set("status", status);
      const response = await fetch(`/api/owner/supplier?${params}`, { cache: "no-store" }); const data = await response.json();
      if (!response.ok || !data.success) throw new Error(data.message); setSuppliers(data.data); setTotal(data.meta.total); setPageCount(data.meta.pageCount);
    } catch (error) { toast.error(error instanceof Error ? error.message : "Failed to load suppliers."); } finally { setLoading(false); }
  }, [page, search, status, sort]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);

  function openCreate() { setEditing(null); setForm(emptyForm()); setFormOpen(true); }
  function openEdit(supplier: Supplier) { setEditing(supplier); setSelected(null); setForm({ name: supplier.name, contactPerson: supplier.contactPerson || "", phone: supplier.phone || "", whatsapp: supplier.whatsapp || "", email: supplier.email || "", address: supplier.address || "", city: supplier.city || "", country: supplier.country || "", taxNumber: supplier.taxNumber || "", status: supplier.status, notes: supplier.notes || "" }); setFormOpen(true); }
  async function save() {
    if (!form.name.trim()) return toast.error("Company name is required.");
    setBusy(true);
    try {
      const response = await fetch(editing ? `/api/owner/supplier/${editing.id}` : "/api/owner/supplier", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
      const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message);
      toast.success(data.message); setFormOpen(false); await load();
    } catch (error) { toast.error(error instanceof Error ? error.message : "Failed to save supplier."); } finally { setBusy(false); }
  }
  async function details(supplier: Supplier) { const response = await fetch(`/api/owner/supplier/${supplier.id}`); const data = await response.json(); if (!response.ok) return toast.error(data.message); setSelected(data.data); }
  async function remove(supplier: Supplier) { if (!confirm(`Delete ${supplier.name}?`)) return; const response = await fetch(`/api/owner/supplier/${supplier.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return toast.error(data.message); toast.success(data.message); setSelected(null); await load(); }
  function exportCsv() { const csv = ["Supplier Code,Company Name,Contact Person,Phone,WhatsApp,Email,City,Country,Status", ...suppliers.map((s) => [s.supplierCode, s.name, s.contactPerson || "", s.phone || "", s.whatsapp || "", s.email || "", s.city || "", s.country || "", s.status].map((v) => `"${String(v).replaceAll('"', '""')}"`).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "suppliers.csv"; link.click(); URL.revokeObjectURL(link.href); }
  async function importCsv(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const rows = (await file.text()).split(/\r?\n/).slice(1).filter(Boolean); let count = 0; for (const row of rows) { const values = row.split(",").map((value) => value.replace(/^"|"$/g, "")); if (!values[1]) continue; const response = await fetch("/api/owner/supplier", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: values[1], contactPerson: values[2], phone: values[3], whatsapp: values[4], email: values[5], city: values[6], country: values[7] }) }); if (response.ok) count++; } event.target.value = ""; toast.success(`${count} supplier${count === 1 ? "" : "s"} imported.`); await load(); }

  return <div className="erp-page erp-page-suppliers space-y-6 p-6"><Toaster position="top-right" />
    <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Suppliers</h1><p className="text-muted-foreground">Manage supplier contacts and inventory relationships</p></div><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><Download className="h-4 w-4" /> Export</button><label className="flex cursor-pointer items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><FileUp className="h-4 w-4" /> Import<input type="file" accept=".csv" onChange={importCsv} className="hidden" /></label><button onClick={openCreate} className="flex items-center gap-2 rounded-lg bg-black px-4 py-2 text-sm text-white"><Plus className="h-4 w-4" /> Add Supplier</button></div></div>
    <div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search code, company, contact, phone, or email..." className="w-full rounded-xl border py-3 pl-10 pr-4" /></div><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="rounded-xl border bg-white px-4 py-3"><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><select value={sort} onChange={(e) => setSort(e.target.value)} className="rounded-xl border bg-white px-4 py-3"><option value="name">Company name</option><option value="recent">Recently added</option></select></div>
    <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[850px] text-sm"><thead className="bg-gray-50"><tr>{["Supplier", "Contact", "Phone", "Email", "Location", "Inventory items", "Status", "Action"].map((heading) => <th key={heading} className="p-4 text-left font-semibold">{heading}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-12 text-center text-gray-500"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin" />Loading suppliers...</td></tr> : suppliers.length === 0 ? <tr><td colSpan={8} className="p-12 text-center text-gray-500">No suppliers found.</td></tr> : suppliers.map((supplier) => <tr key={supplier.id} onClick={() => details(supplier)} className="cursor-pointer border-t hover:bg-gray-50"><td className="p-4"><p className="font-semibold">{supplier.name}</p><p className="text-xs text-gray-500">{supplier.supplierCode}</p></td><td className="p-4">{supplier.contactPerson || "—"}</td><td className="p-4">{supplier.phone || "—"}</td><td className="p-4">{supplier.email || "—"}</td><td className="p-4">{[supplier.city, supplier.country].filter(Boolean).join(", ") || "—"}</td><td className="p-4">{supplier.items.length}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${supplier.status === "ACTIVE" ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-600"}`}>{supplier.status}</span></td><td className="p-4 text-right"><Eye className="h-4 w-4 text-gray-500" /></td></tr>)}</tbody></table></div>
    <div className="flex items-center justify-between text-sm text-gray-500"><span>{total} supplier{total === 1 ? "" : "s"}</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><span>Page {page} of {pageCount}</span><button disabled={page >= pageCount} onClick={() => setPage(page + 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></div>

    {formOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-2xl font-bold">{editing ? "Edit Supplier" : "Add Supplier"}</h2><button onClick={() => setFormOpen(false)}><X /></button></div><div className="grid gap-3 md:grid-cols-2">{fields.map(([key, label]) => <input key={key} placeholder={label} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="rounded-lg border p-3" />)}<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="rounded-lg border bg-white p-3"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><textarea placeholder="Notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="min-h-24 rounded-lg border p-3 md:col-span-2" /></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setFormOpen(false)} className="rounded-lg border px-5 py-2">Cancel</button><button disabled={busy} onClick={save} className="rounded-lg bg-black px-5 py-2 text-white">{busy ? "Saving..." : "Save supplier"}</button></div></div></div>}
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-black/50"><div className="h-full w-full max-w-md overflow-y-auto bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-sm text-gray-500">{selected.supplierCode}</p></div><button onClick={() => setSelected(null)}><X /></button></div><div className="mt-5 space-y-2 rounded-xl bg-gray-50 p-4 text-sm"><p><b>Contact:</b> {selected.contactPerson || "—"}</p><p><b>Phone:</b> {selected.phone || "—"}</p><p><b>WhatsApp:</b> {selected.whatsapp || "—"}</p><p><b>Email:</b> {selected.email || "—"}</p><p><b>Address:</b> {[selected.address, selected.city, selected.country].filter(Boolean).join(", ") || "—"}</p><p><b>Tax number:</b> {selected.taxNumber || "—"}</p><p><b>Status:</b> {selected.status}</p></div><div className="mt-5 rounded-xl border border-dashed bg-slate-50 p-4 text-sm"><h3 className="mb-2 font-semibold">Supplier activity</h3><p className="text-slate-600">{selected.items.length ? `${selected.items.length} inventory item${selected.items.length === 1 ? " is" : "s are"} linked to this supplier.` : "No inventory items are linked yet."}</p><p className="mt-2 text-xs text-slate-500">Purchase/payment totals are shown only when a supplier purchase ledger is connected—no fake zero balances are displayed.</p></div><div className="mt-5"><h3 className="mb-2 font-semibold">Inventory items ({selected.items.length})</h3>{selected.items.map((item) => <p key={item.id} className="border-t py-2 text-sm">{item.name} <span className="text-gray-500">({item.sku})</span></p>)}</div><div className="mt-6 flex gap-2"><button onClick={() => openEdit(selected)} className="flex-1 rounded-lg border py-2"><Pencil className="mx-auto h-4 w-4" /></button><button onClick={() => remove(selected)} className="flex-1 rounded-lg border border-red-200 py-2 text-red-600"><Trash2 className="mx-auto h-4 w-4" /></button></div></div></div>}
  </div>;
}
