import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRestaurantContext } from "@/lib/auth";
const canManage=(role:string)=>["SUPER_ADMIN","OWNER","MANAGER"].includes(role);
const emailTemplates=["WELCOME_EMAIL","NEW_ORDER","RESERVATION_CONFIRMATION","RESERVATION_CANCELLATION","INVOICE","PAYMENT_SUCCESS","PAYMENT_FAILED","PASSWORD_RESET","STAFF_INVITATION","SUBSCRIPTION_RENEWAL","SUBSCRIPTION_EXPIRY"];
const smsTemplates=["OTP","RESERVATION","ORDER_READY","PAYMENT_RECEIVED","PAYMENT_FAILED","LOW_STOCK_ALERT"];
async function seed(restaurantId:number){await prisma.messageTemplate.createMany({data:[...emailTemplates.map(key=>({restaurantId,channel:"EMAIL" as const,key,name:key.replaceAll("_"," "),subject:key.replaceAll("_"," "),body:`Hello {{name}},\n\nThis is your ${key.replaceAll("_"," ")} message.`,enabled:true})),...smsTemplates.map(key=>({restaurantId,channel:"SMS" as const,key,name:key.replaceAll("_"," "),body:`${key.replaceAll("_"," ")} notification for {{name}}.`,enabled:true}))],skipDuplicates:true})}
export async function GET(request:NextRequest){try{const c=await requireRestaurantContext();if(c.errorStatus)return NextResponse.json({success:false,message:c.errorMessage},{status:c.errorStatus});await seed(c.restaurantId!);const p=request.nextUrl.searchParams;const status=p.get("status");const search=p.get("search")?.trim()||"";const [providers,templates,queue,logs]=await Promise.all([prisma.messagingProvider.findMany({where:{restaurantId:c.restaurantId!},select:{id:true,channel:true,provider:true,enabled:true,mode:true,lastTestedAt:true,updatedAt:true}}),prisma.messageTemplate.findMany({where:{restaurantId:c.restaurantId!,...(search?{OR:[{key:{contains:search,mode:"insensitive" as const}},{name:{contains:search,mode:"insensitive" as const}}]}:{})},orderBy:{key:"asc"}}),prisma.messageQueue.findMany({where:{restaurantId:c.restaurantId!,...(status?{status:status as "QUEUED"}: {})},orderBy:{createdAt:"desc"},take:100}),prisma.deliveryLog.findMany({where:{restaurantId:c.restaurantId!},orderBy:{createdAt:"desc"},take:100})]);return NextResponse.json({success:true,data:{providers,templates,queue,logs}})}catch(error){console.error(error);return NextResponse.json({success:false,message:"Failed to load messaging data."},{status:500})}}
export async function POST(request:NextRequest){try{const c=await requireRestaurantContext();if(c.errorStatus)return NextResponse.json({success:false,message:c.errorMessage},{status:c.errorStatus});if(!canManage(c.user!.role))return NextResponse.json({success:false,message:"Forbidden."},{status:403});const body=await request.json();if(body.action==="provider"){const item=await prisma.messagingProvider.upsert({where:{restaurantId_channel_provider:{restaurantId:c.restaurantId!,channel:body.channel,provider:body.provider}},update:{enabled:Boolean(body.enabled),mode:body.mode||"SANDBOX",credentials:body.credentials},create:{restaurantId:c.restaurantId!,channel:body.channel,provider:body.provider,enabled:Boolean(body.enabled),mode:body.mode||"SANDBOX",credentials:body.credentials}});return NextResponse.json({success:true,data:item})}if(body.action==="template"){const item=await prisma.messageTemplate.update({where:{id:Number(body.id)},data:{subject:body.subject||null,body:String(body.body||""),enabled:Boolean(body.enabled)}});return NextResponse.json({success:true,data:item})}if(body.action==="retry"){const item=await prisma.messageQueue.updateMany({where:{id:Number(body.id),restaurantId:c.restaurantId!,status:"FAILED"},data:{status:"QUEUED",lastError:null,scheduledAt:new Date()}});return NextResponse.json({success:item.count>0,message:item.count>0?"Message queued for retry.":"Only failed messages can be retried."},{status:item.count>0?200:404})}if(body.action==="queue"){const item=await prisma.messageQueue.create({data:{restaurantId:c.restaurantId!,channel:body.channel,recipient:String(body.recipient),subject:body.subject||null,body:String(body.body),templateKey:body.templateKey||null}});return NextResponse.json({success:true,data:item},{status:201})}if(body.action==="test"){const item=await prisma.messageQueue.create({data:{restaurantId:c.restaurantId!,channel:body.channel,recipient:String(body.recipient),subject:"Test message",body:"This is a test message from the ERP.",status:"QUEUED"}});return NextResponse.json({success:true,data:item,message:"Test message queued."},{status:201})}return NextResponse.json({success:false,message:"Unsupported messaging action."},{status:400})}catch(error){console.error(error);return NextResponse.json({success:false,message:"Could not save messaging configuration."},{status:500})}}

