"use client";

import { ChangeEvent, useCallback, useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Download, Eye, FileUp, Loader2, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { toast, Toaster } from "sonner";

type Item = { id: number; name: string; sku: string; unit: string; currentStock: string; minimumStock: string; maximumStock: string | null; purchasePrice: string; sellingPrice: string | null; storageLocation: string | null; expiryDate: string | null; barcode: string | null; status: string; notes: string | null; category: { id: number; name: string } | null; supplier: { id: number; name: string } | null };
type Option = { id: number; name: string };
type Form = Record<string, string>;
const blank = (): Form => ({ name: "", sku: "", unit: "pcs", currentStock: "0", minimumStock: "0", maximumStock: "", purchasePrice: "0", sellingPrice: "", categoryId: "", supplierId: "", storageLocation: "", expiryDate: "", barcode: "", status: "ACTIVE", notes: "" });
const status = (item: Item) => item.expiryDate && new Date(item.expiryDate) < new Date() ? "EXPIRED" : Number(item.currentStock) <= 0 ? "OUT_OF_STOCK" : Number(item.currentStock) <= Number(item.minimumStock) ? "LOW_STOCK" : "IN_STOCK";
const styles: Record<string, string> = { IN_STOCK: "bg-green-100 text-green-700", LOW_STOCK: "bg-yellow-100 text-yellow-700", OUT_OF_STOCK: "bg-red-100 text-red-700", EXPIRED: "bg-purple-100 text-purple-700" };

export default function InventoryPage() {
  const [items, setItems] = useState<Item[]>([]); const [categories, setCategories] = useState<Option[]>([]); const [suppliers, setSuppliers] = useState<Option[]>([]);
  const [summary, setSummary] = useState({ total: 0, low: 0, out: 0, expired: 0 }); const [page, setPage] = useState(1); const [pageCount, setPageCount] = useState(1); const [total, setTotal] = useState(0);
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState("ALL"); const [sort, setSort] = useState("name"); const [loading, setLoading] = useState(true);
  const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [form, setForm] = useState<Form>(blank()); const [selected, setSelected] = useState<Item | null>(null);
  const [movement, setMovement] = useState({ type: "STOCK_IN", quantity: "", reason: "" }); const [history, setHistory] = useState<{ type: string; quantity: string; previousStock: string; newStock: string; reason: string | null; createdAt: string }[]>([]); const [busy, setBusy] = useState(false);

  const load = useCallback(async () => { setLoading(true); try { const p = new URLSearchParams({ page: String(page), pageSize: "10", sort, search }); if (filter !== "ALL") p.set("filter", filter); const res = await fetch(`/api/owner/inventory?${p}`, { cache: "no-store" }); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.message); setItems(data.data); setCategories(data.options.categories); setSuppliers(data.options.suppliers); setSummary(data.summary); setTotal(data.meta.total); setPageCount(data.meta.pageCount); } catch (e) { toast.error(e instanceof Error ? e.message : "Failed to load inventory."); } finally { setLoading(false); } }, [page, search, filter, sort]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);

  function edit(item: Item) { setEditing(item); setSelected(null); setForm({ name: item.name, sku: item.sku, unit: item.unit, currentStock: item.currentStock, minimumStock: item.minimumStock, maximumStock: item.maximumStock || "", purchasePrice: item.purchasePrice, sellingPrice: item.sellingPrice || "", categoryId: item.category?.id.toString() || "", supplierId: item.supplier?.id.toString() || "", storageLocation: item.storageLocation || "", expiryDate: item.expiryDate ? item.expiryDate.slice(0, 10) : "", barcode: item.barcode || "", status: item.status, notes: item.notes || "" }); setFormOpen(true); }
  async function save() { setBusy(true); try { const res = await fetch(editing ? `/api/owner/inventory/${editing.id}` : "/api/owner/inventory", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.message); toast.success(data.message); setFormOpen(false); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : "Save failed."); } finally { setBusy(false); } }
  async function remove(item: Item) { if (!confirm(`Delete ${item.name}?`)) return; const res = await fetch(`/api/owner/inventory/${item.id}`, { method: "DELETE" }); const data = await res.json(); if (!res.ok) return toast.error(data.message); toast.success(data.message); setSelected(null); await load(); }
  async function openDetails(item: Item) { setSelected(item); const res = await fetch(`/api/owner/inventory/${item.id}`); const data = await res.json(); if (res.ok) setHistory(data.history); }
  async function move() { if (!selected) return; setBusy(true); try { const res = await fetch(`/api/owner/inventory/${selected.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(movement) }); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.message); toast.success(data.message); setMovement({ type: "STOCK_IN", quantity: "", reason: "" }); setSelected(null); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : "Movement failed."); } finally { setBusy(false); } }
  function exportCsv() { const csv = ["Name,SKU,Unit,Current Stock,Minimum Stock,Purchase Price,Status", ...items.map((i) => [i.name, i.sku, i.unit, i.currentStock, i.minimumStock, i.purchasePrice, status(i)].map((v) => `"${String(v).replaceAll('"', '""')}"`).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "inventory.csv"; link.click(); URL.revokeObjectURL(link.href); }
  async function importCsv(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const lines = (await file.text()).split(/\r?\n/).slice(1).filter(Boolean); let count = 0; for (const line of lines) { const values = line.split(",").map((v) => v.replace(/^"|"$/g, "")); if (values.length < 3) continue; const res = await fetch("/api/owner/inventory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: values[0], sku: values[1], unit: values[2], currentStock: values[3] || 0, minimumStock: values[4] || 0, purchasePrice: values[5] || 0 }) }); if (res.ok) count++; } toast.success(`${count} item${count === 1 ? "" : "s"} imported.`); event.target.value = ""; await load(); }

  return <div className="erp-page erp-page-inventory space-y-6 p-6"><Toaster position="top-right" /><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Inventory</h1><p className="text-muted-foreground">Track stock levels, costs, and movements</p></div><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><Download className="h-4 w-4" /> Export</button><label className="flex cursor-pointer items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><FileUp className="h-4 w-4" /> Import<input type="file" accept=".csv" onChange={importCsv} className="hidden" /></label><button onClick={() => { setEditing(null); setForm(blank()); setFormOpen(true); }} className="flex items-center gap-2 rounded-lg bg-black px-4 py-2 text-sm text-white"><Plus className="h-4 w-4" /> Add Item</button></div></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Total items", summary.total, "ALL"], ["Low stock", summary.low, "LOW_STOCK"], ["Out of stock", summary.out, "OUT_OF_STOCK"], ["Expired", summary.expired, "EXPIRED"]].map(([label, value, key]) => <button key={String(key)} onClick={() => { setFilter(String(key)); setPage(1); }} className={`rounded-xl border bg-white p-4 text-left shadow-sm ${filter === key ? "border-black" : ""}`}><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></button>)}</div>
    <div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search item, SKU, or barcode..." className="w-full rounded-xl border py-3 pl-10 pr-4" /></div><select value={filter} onChange={(e) => { setFilter(e.target.value); setPage(1); }} className="rounded-xl border bg-white px-4"><option value="ALL">All stock status</option><option value="IN_STOCK">In stock</option><option value="LOW_STOCK">Low stock</option><option value="OUT_OF_STOCK">Out of stock</option><option value="EXPIRED">Expired</option></select><select value={sort} onChange={(e) => setSort(e.target.value)} className="rounded-xl border bg-white px-4"><option value="name">Name</option><option value="stock">Lowest stock</option></select></div>
    <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[850px] text-sm"><thead className="bg-gray-50"><tr>{["Item", "SKU", "Category", "Stock", "Purchase price", "Supplier", "Status", "Action"].map((h) => <th key={h} className="p-4 text-left font-semibold">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-12 text-center text-gray-500"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin" />Loading inventory...</td></tr> : items.length === 0 ? <tr><td colSpan={8} className="p-12 text-center text-gray-500">No inventory items found.</td></tr> : items.map((item) => <tr key={item.id} onClick={() => openDetails(item)} className="cursor-pointer border-t hover:bg-gray-50"><td className="p-4 font-semibold">{item.name}</td><td className="p-4 text-gray-600">{item.sku}</td><td className="p-4">{item.category?.name || "—"}</td><td className="p-4">{item.currentStock} {item.unit}<span className="block text-xs text-gray-400">min {item.minimumStock}</span></td><td className="p-4">${Number(item.purchasePrice).toFixed(2)}</td><td className="p-4">{item.supplier?.name || "—"}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${styles[status(item)]}`}>{status(item).replace("_", " ")}</span></td><td className="p-4 text-right"><Eye className="h-4 w-4 text-gray-500" /></td></tr>)}</tbody></table></div>
    <div className="flex items-center justify-between text-sm text-gray-500"><span>{total} item{total === 1 ? "" : "s"}</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><span>Page {page} of {pageCount}</span><button disabled={page >= pageCount} onClick={() => setPage(page + 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></div>

    {formOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-2xl font-bold">{editing ? "Edit item" : "Add inventory item"}</h2><button onClick={() => setFormOpen(false)}><X /></button></div><div className="grid gap-3 md:grid-cols-3">{[["name","Item name"],["sku","SKU"],["unit","Unit"],["currentStock","Current stock"],["minimumStock","Minimum stock"],["maximumStock","Maximum stock"],["purchasePrice","Purchase price"],["sellingPrice","Selling price"],["storageLocation","Storage location"],["expiryDate","Expiry date"],["barcode","Barcode"]].map(([key, label]) => <input key={key} type={key.includes("Price") || key.includes("Stock") ? "number" : key === "expiryDate" ? "date" : "text"} placeholder={label} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="rounded-lg border p-3" />)}<select value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })} className="rounded-lg border bg-white p-3"><option value="">Category</option>{categories.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select><select value={form.supplierId} onChange={(e) => setForm({ ...form, supplierId: e.target.value })} className="rounded-lg border bg-white p-3"><option value="">Supplier</option>{suppliers.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="rounded-lg border bg-white p-3"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><textarea placeholder="Notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="min-h-20 rounded-lg border p-3 md:col-span-3" /></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setFormOpen(false)} className="rounded-lg border px-5 py-2">Cancel</button><button disabled={busy} onClick={save} className="rounded-lg bg-black px-5 py-2 text-white">{busy ? "Saving..." : "Save item"}</button></div></div></div>}
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-black/50"><div className="h-full w-full max-w-md overflow-y-auto bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-sm text-gray-500">{selected.sku}</p></div><button onClick={() => setSelected(null)}><X /></button></div><div className="mt-5 rounded-xl bg-gray-50 p-4 text-sm"><p><b>Current stock:</b> {selected.currentStock} {selected.unit}</p><p><b>Minimum:</b> {selected.minimumStock} {selected.unit}</p><p><b>Location:</b> {selected.storageLocation || "—"}</p><p><b>Supplier:</b> {selected.supplier?.name || "—"}</p><p><b>Expiry:</b> {selected.expiryDate ? new Date(selected.expiryDate).toLocaleDateString() : "—"}</p></div><div className="mt-5 grid grid-cols-2 gap-2"><select value={movement.type} onChange={(e) => setMovement({ ...movement, type: e.target.value })} className="rounded-lg border p-2"><option value="STOCK_IN">Stock in</option><option value="STOCK_OUT">Stock out</option><option value="ADJUSTMENT">Adjustment</option></select><input type="number" min="0" placeholder="Quantity" value={movement.quantity} onChange={(e) => setMovement({ ...movement, quantity: e.target.value })} className="rounded-lg border p-2" /><input placeholder="Reason" value={movement.reason} onChange={(e) => setMovement({ ...movement, reason: e.target.value })} className="rounded-lg border p-2 col-span-2" /><button disabled={busy} onClick={move} className="rounded-lg bg-black py-2 text-sm text-white col-span-2">Record movement</button></div><div className="mt-6"><h3 className="mb-2 font-semibold">Stock history</h3>{history.map((m, i) => <div key={i} className="border-t py-2 text-xs"><b>{m.type.replace("_", " ")}</b> · {m.quantity} · {m.previousStock} → {m.newStock}<p className="text-gray-500">{m.reason || "No reason"} · {new Date(m.createdAt).toLocaleString()}</p></div>)}</div><div className="mt-6 flex gap-2"><button onClick={() => edit(selected)} className="flex-1 rounded-lg border py-2"><Pencil className="mx-auto h-4 w-4" /></button><button onClick={() => remove(selected)} className="flex-1 rounded-lg border border-red-200 py-2 text-red-600"><Trash2 className="mx-auto h-4 w-4" /></button></div></div></div>}
  </div>;
}
