"use client";

import { useState } from "react";
import { Eye, EyeOff, ArrowRight, Loader2, Lock, Mail, UtensilsCrossed, ShieldCheck, BarChart3, Layers3 } from "lucide-react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const router = useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [showPassword,setShowPassword]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const handleLogin=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{const res=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const data=await res.json();if(res.ok)router.push(data.user?.role === "SUPER_ADMIN" ? "/dashboard/restaurants/all" : "/dashboard");else setError(data.message||"Login failed");}catch{setError("Something went wrong");}finally{setLoading(false);}};
  return <main className="relative min-h-dvh overflow-hidden bg-[#f2f4f9] p-3 sm:p-5 lg:p-7">
    <div className="pointer-events-none absolute -left-48 -top-48 h-[34rem] w-[34rem] rounded-full bg-indigo-200/30 blur-3xl"/><div className="pointer-events-none absolute -bottom-48 right-0 h-[30rem] w-[30rem] rounded-full bg-cyan-100/45 blur-3xl"/>
    <div className="relative mx-auto grid min-h-[calc(100dvh-1.5rem)] max-w-[1380px] overflow-hidden rounded-[30px] border border-white/80 bg-white shadow-[0_30px_100px_rgba(15,23,42,.12)] sm:min-h-[calc(100dvh-2.5rem)] lg:grid-cols-[1.08fr_.92fr]">
      <section className="relative hidden overflow-hidden bg-[#10162a] p-10 text-white lg:flex lg:flex-col lg:justify-between xl:p-14">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_12%,rgba(99,102,241,.35),transparent_28rem),radial-gradient(circle_at_90%_75%,rgba(6,182,212,.13),transparent_22rem)]"/><div className="absolute -right-28 top-28 h-72 w-72 rotate-12 rounded-[48px] border border-white/[.06] bg-white/[.025]"/>
        <div className="relative flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 via-violet-500 to-cyan-500 shadow-[0_12px_35px_rgba(99,102,241,.35)] ring-1 ring-white/20"><UtensilsCrossed size={21}/></div><div><p className="text-lg font-extrabold tracking-[-.03em]">Plateful ERP</p><p className="text-[11px] font-medium uppercase tracking-[.14em] text-slate-500">Restaurant Operations</p></div></div>
        <div className="relative max-w-xl"><span className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-300/15 bg-indigo-400/[.08] px-3 py-1.5 text-xs font-semibold text-indigo-200"><ShieldCheck size={14}/> Secure role-based workspace</span><h1 className="max-w-lg text-[44px] font-extrabold leading-[1.06] tracking-[-.05em] xl:text-[52px]">One command center for modern restaurant operations.</h1><p className="mt-5 max-w-lg text-[15px] leading-7 text-slate-400">A focused ERP experience for orders, reservations, inventory, finance and day-to-day performance — built for clear decisions.</p><div className="mt-8 grid max-w-lg grid-cols-2 gap-3"><div className="rounded-2xl border border-white/[.07] bg-white/[.04] p-4"><BarChart3 className="mb-3 h-5 w-5 text-indigo-300"/><p className="text-sm font-bold">Live performance</p><p className="mt-1 text-xs leading-5 text-slate-500">Revenue and operational insights in one view.</p></div><div className="rounded-2xl border border-white/[.07] bg-white/[.04] p-4"><Layers3 className="mb-3 h-5 w-5 text-cyan-300"/><p className="text-sm font-bold">Unified workflow</p><p className="mt-1 text-xs leading-5 text-slate-500">Manage core restaurant functions without clutter.</p></div></div></div>
        <div className="relative flex items-center gap-3 text-[11px] font-medium text-slate-600"><span>Portfolio SaaS Experience</span><span className="h-1 w-1 rounded-full bg-slate-700"/><span>2026</span></div>
      </section>
      <section className="flex items-center justify-center p-6 sm:p-10 lg:p-14 xl:p-20"><div className="w-full max-w-[430px]">
        <div className="mb-9 lg:hidden"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 via-violet-500 to-cyan-500 text-white shadow-lg"><UtensilsCrossed size={21}/></div><p className="text-lg font-extrabold tracking-tight text-slate-900">Plateful ERP</p></div>
        <div className="mb-8"><p className="mb-2 text-[11px] font-bold uppercase tracking-[.2em] text-indigo-600">Welcome back</p><h2 className="text-[32px] font-extrabold tracking-[-.045em] text-[#151d31] sm:text-[36px]">Sign in to your workspace</h2><p className="mt-2 text-sm leading-6 text-slate-500">Use your account credentials to continue to the management dashboard.</p></div>
        <form onSubmit={handleLogin} className="space-y-5">{error&&<div className="rounded-xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-600">{error}</div>}
          <div><label className="mb-1.5 block text-sm font-semibold text-slate-700">Email address</label><div className="relative"><Mail size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"/><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@restaurant.com" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50/50 pl-10 pr-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-100/70"/></div></div>
          <div><label className="mb-1.5 block text-sm font-semibold text-slate-700">Password</label><div className="relative"><Lock size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"/><input type={showPassword?"text":"password"} required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50/50 pl-10 pr-11 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-100/70"/><button type="button" aria-label={showPassword?"Hide password":"Show password"} onClick={()=>setShowPassword(v=>!v)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-slate-400 hover:bg-white hover:text-slate-700">{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div>
          <button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 via-violet-500 to-indigo-600 px-4 text-sm font-bold text-white shadow-[0_12px_28px_rgba(99,102,241,.24)] transition hover:-translate-y-0.5 hover:shadow-[0_16px_34px_rgba(99,102,241,.3)] disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:translate-y-0">{loading?<><Loader2 size={17} className="animate-spin"/>Signing in...</>:<>Enter dashboard<ArrowRight size={17}/></>}</button>
        </form><div className="mt-8 flex items-center justify-center gap-2 text-[11px] font-medium text-slate-400"><ShieldCheck size={13}/> Protected administrative access</div>
      </div></section>
    </div>
  </main>;
}
