import { createHash } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Prisma } from "@/generated/prisma/client";
import { getSessionUser } from "@/lib/auth";
const allowed=(role:string)=>["SUPER_ADMIN","OWNER"].includes(role);
const checksum=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
async function snapshot(restaurantId:number,type:string){const settings=type==="FULL_DATABASE"||type==="RESTAURANT_DATA"||type==="SETTINGS"?await prisma.restaurantSettings.findUnique({where:{restaurantId}}):null;const data:Record<string, unknown>={generatedAt:new Date().toISOString(),type,settings};if(type==="FULL_DATABASE"||type==="RESTAURANT_DATA"||type==="ORDERS")data.orders=await prisma.order.findMany({where:{restaurantId}});if(type==="FULL_DATABASE"||type==="RESTAURANT_DATA"||type==="CUSTOMERS")data.customers=await prisma.customer.findMany({where:{restaurantId}});if(type==="FULL_DATABASE"||type==="RESTAURANT_DATA"||type==="INVENTORY")data.inventory=await prisma.inventoryItem.findMany({where:{restaurantId}});return data;}
export async function GET(request:NextRequest){try{const user=await getSessionUser();if(!user)return NextResponse.json({success:false,message:"Unauthorized."},{status:401});if(!allowed(user.role))return NextResponse.json({success:false,message:"Only Super Admin and Restaurant Owner can manage backups."},{status:403});const p=request.nextUrl.searchParams;const restaurantId=user.role==="SUPER_ADMIN"?Number(p.get("restaurantId")):user.restaurantId!;if(!restaurantId)return NextResponse.json({success:false,message:"Restaurant is required."},{status:400});const backups=await prisma.backup.findMany({where:{restaurantId},select:{id:true,name:true,type:true,status:true,sizeBytes:true,checksum:true,createdAt:true,completedAt:true,createdBy:{select:{name:true,email:true}}},orderBy:{createdAt:"desc"}});const settings=await prisma.backupSettings.findUnique({where:{restaurantId}});return NextResponse.json({success:true,data:backups,settings});}catch(error){console.error(error);return NextResponse.json({success:false,message:"Failed to load backups."},{status:500})}}
export async function POST(request:NextRequest){try{const user=await getSessionUser();if(!user)return NextResponse.json({success:false,message:"Unauthorized."},{status:401});if(!allowed(user.role))return NextResponse.json({success:false,message:"Forbidden."},{status:403});const body=await request.json();const restaurantId=user.role==="SUPER_ADMIN"?Number(body.restaurantId):user.restaurantId!;const type=String(body.type||"FULL_DATABASE");if(!restaurantId||!["FULL_DATABASE","RESTAURANT_DATA","SETTINGS","INVENTORY","ORDERS","CUSTOMERS"].includes(type))return NextResponse.json({success:false,message:"Valid restaurant and backup type are required."},{status:400});const payload=await snapshot(restaurantId,type);const serialized=JSON.stringify(payload);const backup=await prisma.backup.create({data:{restaurantId,createdById:user.id,name:String(body.name||`${type} backup`),type:type as "FULL_DATABASE",status:"COMPLETED",sizeBytes:Buffer.byteLength(serialized),checksum:checksum(payload),payload: payload as Prisma.InputJsonValue,completedAt:new Date()}});return NextResponse.json({success:true,data:{id:backup.id,name:backup.name,sizeBytes:backup.sizeBytes,status:backup.status}},{status:201});}catch(error){console.error(error);return NextResponse.json({success:false,message:"Backup creation failed."},{status:500})}}
export async function PATCH(request:NextRequest){try{const user=await getSessionUser();if(!user||!allowed(user.role))return NextResponse.json({success:false,message:"Forbidden."},{status:user?403:401});const body=await request.json();const restaurantId=user.role==="SUPER_ADMIN"?Number(body.restaurantId):user.restaurantId!;const settings=await prisma.backupSettings.upsert({where:{restaurantId},update:{...(body.frequency?{frequency:body.frequency}:{}) ,...(body.retentionDays!==undefined?{retentionDays:Math.max(1,Number(body.retentionDays))}:{}),...(body.autoDelete!==undefined?{autoDelete:Boolean(body.autoDelete)}:{}),...(body.storageLocation?{storageLocation:String(body.storageLocation)}:{}),...(body.enabled!==undefined?{enabled:Boolean(body.enabled)}:{})},create:{restaurantId,frequency:body.frequency||"MANUAL",retentionDays:Math.max(1,Number(body.retentionDays)||30),autoDelete:body.autoDelete!==false,storageLocation:body.storageLocation||"DATABASE",enabled:Boolean(body.enabled)}});return NextResponse.json({success:true,data:settings});}catch(error){console.error(error);return NextResponse.json({success:false,message:"Could not save backup settings."},{status:500})}}


