import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRestaurantContext } from "@/lib/auth";
const CATEGORIES = ["RENT", "SALARY", "UTILITIES", "PURCHASE", "MAINTENANCE", "MARKETING", "MISCELLANEOUS"] as const;
const METHODS = ["CASH", "CARD", "ONLINE", "WALLET"] as const;
const STATUSES = ["PENDING", "PAID", "CANCELLED"] as const;
function date(value: unknown) { const parsed = value ? new Date(String(value)) : null; return parsed && !Number.isNaN(parsed.getTime()) ? parsed : null; }
async function find(id: string) { const context = await requireRestaurantContext(); if (context.errorStatus) return { context, expense: null }; const expense = await prisma.expense.findFirst({ where: { id: Number(id), restaurantId: context.restaurantId! }, include: { createdBy: { select: { id: true, name: true } } } }); return { context, expense }; }
export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { context, expense } = await find((await params).id); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); if (!expense) return NextResponse.json({ success: false, message: "Expense not found." }, { status: 404 }); return NextResponse.json({ success: true, data: expense }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Failed to fetch expense." }, { status: 500 }); } }
export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { context, expense } = await find((await params).id); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); if (!expense) return NextResponse.json({ success: false, message: "Expense not found." }, { status: 404 }); const body = await request.json(); const amount = Number(body.amount); const expenseDate = date(body.expenseDate); if (!body.title?.trim() || !Number.isFinite(amount) || amount <= 0 || !expenseDate || !CATEGORIES.includes(body.category) || !METHODS.includes(body.paymentMethod)) return NextResponse.json({ success: false, message: "Title, valid amount, category, payment method, and date are required." }, { status: 400 }); const updated = await prisma.expense.update({ where: { id: expense.id }, data: { title: body.title.trim(), description: body.description?.trim() || null, category: body.category, amount, paymentMethod: body.paymentMethod, expenseDate, status: STATUSES.includes(body.status) ? body.status : expense.status, receiptUrl: body.receiptUrl || null } }); return NextResponse.json({ success: true, message: "Expense updated successfully.", data: updated }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Expense update failed." }, { status: 500 }); } }
export async function DELETE(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { context, expense } = await find((await params).id); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); if (!expense) return NextResponse.json({ success: false, message: "Expense not found." }, { status: 404 }); await prisma.expense.delete({ where: { id: expense.id } }); return NextResponse.json({ success: true, message: "Expense deleted successfully." }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Expense deletion failed." }, { status: 500 }); } }
