"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart, Bar, CartesianGrid, Cell, LineChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Download, Loader2, Printer, RefreshCw, Search } from "lucide-react";
import { toast, Toaster } from "sonner";
import { useRestaurantSettings } from "@/hooks/useRestaurantSettings";

type Report = { range: { from: string; to: string }; data: { summary: { todaySales: number; weeklySales: number; monthlySales: number; totalOrders: number; totalCustomers: number; totalReservations: number; totalRevenue: number; lowStockItems: number }; sales: { revenue: number; bills: number; series: { date: string; sales: number; orders: number }[] }; orders: { total: number; statuses: Record<string, number>; types: Record<string, number>; pending: number; completed: number; cancelled: number }; customers: { newCustomers: number; returningCustomers: number; top: { name: string; orders: number; spending: number }[] }; inventory: { current: number; lowStock: number; outOfStock: number; movements: { type: string; quantity: number; createdAt: string; inventoryItem: { name: string; sku: string } }[] }; reservations: { total: number; statuses: Record<string, number>; completed: number; cancelled: number; noShow: number }; staff: { department: string; status: string; count: number }[] } };
const tabs = ["Overview", "Sales", "Orders", "Customers", "Staff", "Inventory", "Reservations"];
const colors = ["#111827", "#2563eb", "#16a34a", "#ea580c", "#9333ea", "#dc2626"];
const REPORT_TODAY = new Date();
const INITIAL_FROM = new Date(REPORT_TODAY.getTime() - 29 * 86400000).toISOString().slice(0, 10);
const INITIAL_TO = REPORT_TODAY.toISOString().slice(0, 10);
const pretty = (value: string) => value.replaceAll("_", " ");
function Card({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>; }
function ChartBox({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">{title}</h2><div className="h-72">{children}</div></div>; }
export default function ReportsPage() {
  const { money } = useRestaurantSettings();
  const initialFrom = INITIAL_FROM; const today = INITIAL_TO;
  const [from, setFrom] = useState(initialFrom); const [to, setTo] = useState(today); const [report, setReport] = useState<Report | null>(null); const [tab, setTab] = useState("Overview"); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const r = await fetch(`/api/owner/reports?from=${from}&to=${to}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok || !d.success) throw new Error(d.message); setReport(d); } catch (e) { toast.error(e instanceof Error ? e.message : "Failed to load reports."); } finally { setLoading(false); } }, [from, to]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);
  const filteredTop = useMemo(() => report?.data.customers.top.filter(c => !search || c.name.toLowerCase().includes(search.toLowerCase())) || [], [report, search]);
  function exportCsv() { if (!report) return; const rows = [["Report", "Value"], ["Today Sales", report.data.summary.todaySales], ["Weekly Sales", report.data.summary.weeklySales], ["Monthly Sales", report.data.summary.monthlySales], ["Total Orders", report.data.summary.totalOrders], ["Total Customers", report.data.summary.totalCustomers], ["Total Reservations", report.data.summary.totalReservations], ["Total Revenue", report.data.summary.totalRevenue], ["Low Stock Items", report.data.summary.lowStockItems], ...report.data.sales.series.map(x => [x.date, x.sales])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = `report-${from}-${to}.csv`; a.click(); URL.revokeObjectURL(a.href); }
  if (loading && !report) return <div className="p-6"><Loader2 className="animate-spin" /></div>;
  if (!report) return null; const d = report.data;
  const distribution = Object.entries(d.orders.types).map(([name, value]) => ({ name: pretty(name), value })); const reservationData = Object.entries(d.reservations.statuses).map(([name, value]) => ({ name: pretty(name), value }));
  return <div className="erp-page erp-page-reports space-y-6 p-6 print:p-0"><Toaster position="top-right" /><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Reports</h1><p className="text-muted-foreground">Dynamic operational and revenue reports</p></div><div className="flex flex-wrap gap-2"><button onClick={() => window.print()} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><Printer className="h-4 w-4" /> Print / PDF</button><button onClick={exportCsv} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><Download className="h-4 w-4" /> Export Excel</button><button onClick={load} className="rounded-lg border bg-white p-2"><RefreshCw className="h-4 w-4" /></button></div></div>
  <div className="flex flex-col gap-3 rounded-xl border bg-white p-4 md:flex-row md:items-center"><label className="text-sm font-medium">From <input type="date" value={from} onChange={e => setFrom(e.target.value)} className="ml-2 rounded-lg border p-2" /></label><label className="text-sm font-medium">To <input type="date" value={to} onChange={e => setTo(e.target.value)} className="ml-2 rounded-lg border p-2" /></label><div className="relative flex-1 md:ml-auto"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search top customers..." className="w-full rounded-lg border py-2 pl-9 pr-3" /></div></div>
  <div className="flex flex-wrap gap-2 print:hidden">{tabs.map(item => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-4 py-2 text-sm ${tab === item ? "bg-black text-white" : "border bg-white"}`}>{item}</button>)}</div>
  {(tab === "Overview" || tab === "Sales") && <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Today's Sales" value={money(d.summary.todaySales)} /><Card label="Weekly Sales" value={money(d.summary.weeklySales)} /><Card label="Monthly Sales" value={money(d.summary.monthlySales)} /><Card label="Total Revenue" value={money(d.summary.totalRevenue)} /><Card label="Total Orders" value={d.summary.totalOrders} /><Card label="Total Customers" value={d.summary.totalCustomers} /><Card label="Total Reservations" value={d.summary.totalReservations} /><Card label="Low Stock Items" value={d.summary.lowStockItems} /></div><ChartBox title="Sales trend"><ResponsiveContainer width="100%" height="100%"><LineChart data={d.sales.series}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis /><Tooltip /><Line type="monotone" dataKey="sales" stroke="#111827" strokeWidth={2} /></LineChart></ResponsiveContainer></ChartBox></>}
  {(tab === "Overview" || tab === "Orders") && <div className="grid gap-6 lg:grid-cols-2"><ChartBox title="Orders by type"><ResponsiveContainer width="100%" height="100%"><BarChart data={distribution}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="value" fill="#2563eb" /></BarChart></ResponsiveContainer></ChartBox><div className="grid grid-cols-3 gap-4"><Card label="Pending Orders" value={d.orders.pending} /><Card label="Completed Orders" value={d.orders.completed} /><Card label="Cancelled Orders" value={d.orders.cancelled} /></div></div>}
  {(tab === "Overview" || tab === "Customers") && <div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">Top Customers</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Customer</th><th className="p-3">Orders</th><th className="p-3">Spending</th></tr></thead><tbody>{filteredTop.map(c => <tr key={c.name} className="border-b"><td className="p-3">{c.name}</td><td className="p-3">{c.orders}</td><td className="p-3">{money(c.spending)}</td></tr>)}{filteredTop.length === 0 && <tr><td colSpan={3} className="p-6 text-center text-gray-500">No customer activity in this range.</td></tr>}</tbody></table></div><p className="mt-3 text-sm text-gray-500">New customers: {d.customers.newCustomers} · Returning customers: {d.customers.returningCustomers}</p></div>}
  {(tab === "Overview" || tab === "Reservations") && <div className="grid gap-6 lg:grid-cols-2"><ChartBox title="Reservation status"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={reservationData} dataKey="value" nameKey="name" outerRadius={95} label>{reservationData.map((_, i) => <Cell key={i} fill={colors[i % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></ChartBox><div className="grid grid-cols-3 gap-4"><Card label="Completed" value={d.reservations.completed} /><Card label="Cancelled" value={d.reservations.cancelled} /><Card label="No Shows" value={d.reservations.noShow} /></div></div>}
  {(tab === "Overview" || tab === "Inventory") && <div className="grid gap-4 sm:grid-cols-3"><Card label="Current Stock Items" value={d.inventory.current} /><Card label="Low Stock" value={d.inventory.lowStock} /><Card label="Out of Stock" value={d.inventory.outOfStock} /></div>}
  {tab === "Staff" && <div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">Staff by department and status</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{d.staff.map(x => <Card key={`${x.department}-${x.status}`} label={`${pretty(x.department)} · ${pretty(x.status)}`} value={x.count} />)}</div></div>}
  {tab === "Inventory" && <div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">Recent stock movement</h2>{d.inventory.movements.length === 0 ? <p className="text-sm text-gray-500">No stock movements in this range.</p> : <div className="space-y-2 text-sm">{d.inventory.movements.slice(0, 20).map((m, i) => <p key={`${m.createdAt}-${i}`} className="border-b py-2">{pretty(m.type)} · {m.inventoryItem.name} · {m.quantity} · {new Date(m.createdAt).toLocaleString()}</p>)}</div>}</div>}
  </div>;
}
