import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRestaurantContext } from "@/lib/auth";
const CATEGORIES = ["RENT", "SALARY", "UTILITIES", "PURCHASE", "MAINTENANCE", "MARKETING", "MISCELLANEOUS"] as const;
const METHODS = ["CASH", "CARD", "ONLINE", "WALLET"] as const;
const STATUSES = ["PENDING", "PAID", "CANCELLED"] as const;
function number(restaurantId: number) { return `EXP-${restaurantId}-${Date.now().toString(36).toUpperCase()}${Math.floor(Math.random() * 900 + 100)}`; }
function date(value: unknown) { const parsed = value ? new Date(String(value)) : new Date(); return Number.isNaN(parsed.getTime()) ? null : parsed; }
export async function GET(request: NextRequest) { try { const context = await requireRestaurantContext(); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); const p = request.nextUrl.searchParams; const page = Math.max(1, Number(p.get("page")) || 1); const pageSize = Math.min(50, Math.max(1, Number(p.get("pageSize")) || 10)); const search = p.get("search")?.trim() || ""; const category = p.get("category"); const status = p.get("status"); const from = p.get("from"); const to = p.get("to"); const where = { restaurantId: context.restaurantId!, ...(CATEGORIES.includes(category as (typeof CATEGORIES)[number]) ? { category: category as (typeof CATEGORIES)[number] } : {}), ...(STATUSES.includes(status as (typeof STATUSES)[number]) ? { status: status as (typeof STATUSES)[number] } : {}), ...(from || to ? { expenseDate: { ...(from ? { gte: new Date(`${from}T00:00:00`) } : {}), ...(to ? { lte: new Date(`${to}T23:59:59.999`) } : {}) } } : {}), ...(search ? { OR: [{ expenseNumber: { contains: search, mode: "insensitive" as const } }, { title: { contains: search, mode: "insensitive" as const } }, { description: { contains: search, mode: "insensitive" as const } }] } : {}) }; const [data, total] = await Promise.all([prisma.expense.findMany({ where, include: { createdBy: { select: { id: true, name: true } } }, orderBy: { expenseDate: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), prisma.expense.count({ where })]); return NextResponse.json({ success: true, data, meta: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) } }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Failed to fetch expenses." }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { const context = await requireRestaurantContext(); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); const body = await request.json(); const amount = Number(body.amount); const expenseDate = date(body.expenseDate); if (!body.title?.trim() || !Number.isFinite(amount) || amount <= 0 || !expenseDate || !CATEGORIES.includes(body.category) || !METHODS.includes(body.paymentMethod)) return NextResponse.json({ success: false, message: "Title, valid amount, category, payment method, and date are required." }, { status: 400 }); const expense = await prisma.expense.create({ data: { restaurantId: context.restaurantId!, expenseNumber: number(context.restaurantId!), title: body.title.trim(), description: body.description?.trim() || null, category: body.category, amount, paymentMethod: body.paymentMethod, expenseDate, status: STATUSES.includes(body.status) ? body.status : "PAID", receiptUrl: body.receiptUrl || null, createdById: context.user!.id } }); return NextResponse.json({ success: true, message: "Expense created successfully.", data: expense }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Expense creation failed." }, { status: 500 }); } }
