import Link from "next/link";
import { ArrowRight, ChefHat, Check, ClipboardList, PackageCheck, ReceiptText, ShieldCheck, UtensilsCrossed } from "lucide-react";
import DemoLauncher from "@/components/demo/DemoLauncher";

const flow = [
  { icon: ClipboardList, title: "1. Menu", text: "Review the sample menu and recipe setup." },
  { icon: UtensilsCrossed, title: "2. POS", text: "Create a dine-in or takeaway order." },
  { icon: ChefHat, title: "3. Kitchen", text: "Move the ticket through preparation." },
  { icon: ReceiptText, title: "4. Bill", text: "Generate the sample bill and complete the flow." },
];

export default function Home() {
  const contactUrl = process.env.NEXT_PUBLIC_PORTFOLIO_CONTACT_URL;
  return <main className="min-h-dvh bg-[#07111f] text-white">
    <nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-lime-300 text-slate-950"><UtensilsCrossed size={20}/></span><span className="text-base font-extrabold">RestaurantOS</span></Link><div className="flex items-center gap-2"><Link href="/login" className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-300 hover:bg-white/5 hover:text-white">Owner / Staff Login</Link>{contactUrl?<a href={contactUrl} className="hidden rounded-xl border border-white/15 px-4 py-2.5 text-sm font-semibold sm:inline-flex">Contact Admin</a>:null}</div></nav>
    <section className="relative overflow-hidden border-y border-white/[.07]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(132,204,22,.15),transparent_30rem),radial-gradient(circle_at_85%_45%,rgba(56,189,248,.11),transparent_28rem)]"/><div className="relative mx-auto grid max-w-7xl gap-14 px-5 py-20 lg:grid-cols-2 lg:px-8 lg:py-28"><div className="self-center"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-lime-300/20 bg-lime-300/[.08] px-3 py-1.5 text-xs font-bold text-lime-200"><ShieldCheck size={14}/>Isolated one-hour workspace</div><h1 className="text-5xl font-black leading-[.98] tracking-[-.06em] sm:text-6xl">Test the restaurant flow, end to end.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-400">Explore the working menu, POS, kitchen, billing and inventory workflow with fictional data and no signup.</p><div className="mt-8 flex flex-wrap gap-3"><DemoLauncher/><Link href="/login" className="inline-flex h-13 items-center gap-2 rounded-xl border border-white/15 px-6 text-sm font-bold hover:bg-white/5">Owner / Staff Login<ArrowRight size={16}/></Link></div><p className="mt-5 text-xs text-slate-500">No signup · Sample data · Access ends 60 minutes after first provisioning</p></div>
      <div className="relative"><div className="absolute -inset-8 rounded-full bg-sky-400/10 blur-3xl"/><div className="relative rounded-[28px] border border-white/10 bg-[#0d1a2a] p-6 shadow-[0_35px_100px_rgba(0,0,0,.45)]"><p className="text-xs font-bold uppercase tracking-[.2em] text-lime-300">Guided demo workflow</p><div className="mt-5 grid gap-3">{flow.map(({icon:Icon,title,text})=><div key={title} className="flex items-center gap-4 rounded-2xl border border-white/[.07] bg-white/[.035] p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-lime-300/10 text-lime-300"><Icon size={18}/></span><div><h2 className="font-extrabold">{title}</h2><p className="mt-1 text-sm text-slate-400">{text}</p></div></div>)}</div><div className="mt-4 flex items-center gap-3 rounded-2xl border border-sky-400/15 bg-sky-400/[.06] p-4 text-sm text-slate-300"><PackageCheck size={19} className="shrink-0 text-sky-300"/>Inventory updates when recipe-linked paid orders close.</div></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-lime-300">Working product tour</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-4xl">A focused buyer demo</h2><p className="mt-4 max-w-2xl leading-7 text-slate-400">Each visitor receives a separate temporary restaurant. Changes survive reloads during the active session and cannot affect another visitor.</p><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{flow.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><Icon size={20} className="text-lime-300"/><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></section>
    <section className="border-y border-white/[.07] bg-white/[.025]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-2 lg:px-8"><div><h2 className="text-3xl font-black">Safe by design</h2><p className="mt-4 max-w-xl leading-7 text-slate-400">The public demo cannot access Super Admin, staff invitations, real payments, external messages or backups.</p></div><div className="grid gap-3 sm:grid-cols-2">{["Separate restaurant per visitor","Server-enforced expiry","Fictional records only","Recoverable cleanup"].map(item=><div key={item} className="flex items-center gap-3 rounded-xl border border-white/[.07] bg-[#07111f] px-4 py-3 text-sm font-semibold"><Check size={16} className="text-lime-300"/>{item}</div>)}</div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-10 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>RestaurantOS · Portfolio demonstration</p><div className="flex gap-5"><Link href="/login" className="hover:text-white">Owner / Staff Login</Link>{contactUrl?<a href={contactUrl} className="hover:text-white">Contact Admin</a>:<span title="Configure NEXT_PUBLIC_PORTFOLIO_CONTACT_URL">Contact link pending</span>}</div></footer>
  </main>;
}
