import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRestaurantContext } from "@/lib/auth";
const STATUSES = ["ACTIVE", "INACTIVE", "BLOCKED", "VIP"] as const;
const GENDERS = ["MALE", "FEMALE", "OTHER"] as const;
function validDate(value: unknown) { if (!value) return null; const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? null : date; }
async function getCustomer(id: string) { const context = await requireRestaurantContext(); if (context.errorStatus) return { context, customer: null }; const customer = await prisma.customer.findFirst({ where: { id: Number(id), restaurantId: context.restaurantId! } }); return { context, customer }; }
async function usage(restaurantId: number, customer: { id: number; phone: string }) { const [orders, reservations] = await Promise.all([prisma.order.findMany({ where: { restaurantId, customerPhone: customer.phone, status: { not: "CANCELLED" } }, include: { bill: { select: { grandTotal: true } }, items: { select: { nameSnapshot: true, quantity: true, menuItem: { select: { category: { select: { name: true } } } } } } }, orderBy: { createdAt: "desc" } }), prisma.reservation.findMany({ where: { restaurantId, customerId: customer.id }, orderBy: { reservationAt: "desc" }, take: 20 })]); const total = orders.reduce((sum, order) => sum + Number(order.bill?.grandTotal ?? order.totalAmount), 0); const items = new Map<string, number>(), categories = new Map<string, number>(); for (const order of orders) for (const item of order.items) { items.set(item.nameSnapshot, (items.get(item.nameSnapshot) || 0) + item.quantity); const category = item.menuItem.category?.name; if (category) categories.set(category, (categories.get(category) || 0) + item.quantity); } const top = (m: Map<string, number>) => [...m.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] || null; return { totalOrders: orders.length, totalReservations: reservations.filter(r => r.status !== "CANCELLED").length, totalSpending: total, averageOrderValue: orders.length ? total / orders.length : 0, lastVisit: orders[0]?.createdAt || null, favouriteItem: top(items), favouriteCategory: top(categories), orders, reservations }; }
export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { context, customer } = await getCustomer((await params).id); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); if (!customer) return NextResponse.json({ success: false, message: "Customer not found." }, { status: 404 }); return NextResponse.json({ success: true, data: { ...customer, stats: await usage(context.restaurantId!, customer) } }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Failed to fetch customer." }, { status: 500 }); } }
export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { context, customer } = await getCustomer((await params).id); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); if (!customer) return NextResponse.json({ success: false, message: "Customer not found." }, { status: 404 }); const body = await request.json(); if (!body.name?.trim() || !body.phone?.trim()) return NextResponse.json({ success: false, message: "Name and phone are required." }, { status: 400 }); const duplicate = await prisma.customer.findFirst({ where: { restaurantId: context.restaurantId!, id: { not: customer.id }, OR: [{ phone: body.phone.trim() }, ...(body.email?.trim() ? [{ email: body.email.trim().toLowerCase() }] : [])] } }); if (duplicate) return NextResponse.json({ success: false, message: "Phone or email is already registered." }, { status: 409 }); const updated = await prisma.customer.update({ where: { id: customer.id }, data: { name: body.name.trim(), profileImage: body.profileImage || null, phone: body.phone.trim(), email: body.email?.trim().toLowerCase() || null, dateOfBirth: validDate(body.dateOfBirth), gender: GENDERS.includes(body.gender) ? body.gender : null, address: body.address?.trim() || null, city: body.city?.trim() || null, notes: body.notes?.trim() || null, registrationDate: validDate(body.registrationDate) || customer.registrationDate, status: STATUSES.includes(body.status) ? body.status : customer.status } }); return NextResponse.json({ success: true, message: "Customer updated successfully.", data: updated }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Customer update failed." }, { status: 500 }); } }
export async function DELETE(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { context, customer } = await getCustomer((await params).id); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); if (!customer) return NextResponse.json({ success: false, message: "Customer not found." }, { status: 404 }); const [orders, reservations] = await Promise.all([prisma.order.count({ where: { restaurantId: context.restaurantId!, customerPhone: customer.phone } }), prisma.reservation.count({ where: { restaurantId: context.restaurantId!, customerId: customer.id } })]); if (orders || reservations) { await prisma.customer.update({ where: { id: customer.id }, data: { status: "INACTIVE" } }); return NextResponse.json({ success: true, message: "Customer has transactions and was marked inactive." }); } await prisma.customer.delete({ where: { id: customer.id } }); return NextResponse.json({ success: true, message: "Customer deleted successfully." }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Customer deletion failed." }, { status: 500 }); } }
