import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRestaurantContext } from "@/lib/auth";

const modules = ["Dashboard", "Restaurant", "Tables", "Reservations", "Orders", "Kitchen", "Billing", "Menu", "Categories", "Inventory", "Suppliers", "Staff", "Customers", "Reports", "Expenses", "Finance", "Settings", "Notifications"];
const actions = ["View", "Create", "Update", "Delete", "Export", "Import", "Approve", "Reject", "Print"];
const defaults = ["Super Admin", "Restaurant Owner", "Manager", "Cashier", "Waiter", "Chef", "Kitchen Staff", "Inventory Manager", "Accountant"];

async function admin() { const context = await requireRestaurantContext(); if (context.errorStatus) return { context, allowed: false }; return { context, allowed: ["SUPER_ADMIN", "OWNER", "MANAGER"].includes(context.user!.role) }; }
async function seed(restaurantId: number) {
  await Promise.all(modules.flatMap(module => actions.map(action => prisma.permission.upsert({ where: { module_action: { module, action } }, update: {}, create: { module, action } }))));
  for (const name of defaults) await prisma.role.upsert({ where: { restaurantId_name: { restaurantId, name } }, update: {}, create: { restaurantId, name, isSystem: true } });
}
export async function GET(request: NextRequest) { try { const { context, allowed } = await admin(); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); if (!allowed) return NextResponse.json({ success: false, message: "You do not have permission to manage roles." }, { status: 403 }); await seed(context.restaurantId!); const p = request.nextUrl.searchParams; const search = p.get("search")?.trim() || ""; const page = Math.max(1, Number(p.get("page")) || 1); const pageSize = Math.min(50, Math.max(1, Number(p.get("pageSize")) || 10)); const where = { restaurantId: context.restaurantId!, ...(search ? { name: { contains: search, mode: "insensitive" as const } } : {}) }; const [roles, total, permissions, users] = await Promise.all([prisma.role.findMany({ where, include: { permissions: { include: { permission: true } }, _count: { select: { assignments: true } } }, orderBy: { name: "asc" }, skip: (page - 1) * pageSize, take: pageSize }), prisma.role.count({ where }), prisma.permission.findMany({ orderBy: [{ module: "asc" }, { action: "asc" }] }), prisma.userRoleAssignment.findMany({ where: { restaurantId: context.restaurantId! }, include: { user: { select: { id: true, name: true, email: true, role: true } }, role: { select: { id: true, name: true } } }, orderBy: { user: { name: "asc" } } })]); return NextResponse.json({ success: true, data: roles, permissions, users, meta: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) } }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Failed to load roles." }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { const { context, allowed } = await admin(); if (context.errorStatus) return NextResponse.json({ success: false, message: context.errorMessage }, { status: context.errorStatus }); if (!allowed) return NextResponse.json({ success: false, message: "You do not have permission to manage roles." }, { status: 403 }); const body = await request.json(); const name = String(body.name || "").trim(); if (!name) return NextResponse.json({ success: false, message: "Role name is required." }, { status: 400 }); const role = await prisma.role.create({ data: { restaurantId: context.restaurantId!, name, description: body.description ? String(body.description).trim() : null } }); let permissionIds = Array.isArray(body.permissionIds) ? body.permissionIds.map((permissionId: number) => Number(permissionId)) : []; if (!permissionIds.length && body.cloneRoleId) { const source = await prisma.role.findFirst({ where: { id: Number(body.cloneRoleId), restaurantId: context.restaurantId! }, select: { permissions: { select: { permissionId: true } } } }); permissionIds = source?.permissions.map(item => item.permissionId) || []; } if (permissionIds.length) await prisma.rolePermission.createMany({ data: permissionIds.map((permissionId: number) => ({ roleId: role.id, permissionId })), skipDuplicates: true }); return NextResponse.json({ success: true, data: role }, { status: 201 }); } catch (error) { console.error(error); return NextResponse.json({ success: false, message: "Could not create role. Check for duplicate names." }, { status: 500 }); } }
export { modules, actions };

