"use client";
import { ChangeEvent, useCallback, useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Download, Eye, FileUp, Loader2, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { toast, Toaster } from "sonner";

type Customer = { id: number; customerCode: string; name: string; profileImage: string | null; phone: string; email: string | null; dateOfBirth: string | null; gender: string | null; address: string | null; city: string | null; notes: string | null; registrationDate: string; status: string; stats: { totalOrders: number; totalReservations: number; totalSpending: number; averageOrderValue: number; lastVisit: string | null; favouriteItem: string | null; favouriteCategory: string | null } };
type Form = Record<string, string>;
const statuses = ["ACTIVE", "INACTIVE", "BLOCKED", "VIP"];
const blank = (): Form => ({ name: "", phone: "", email: "", profileImage: "", dateOfBirth: "", gender: "", address: "", city: "", notes: "", registrationDate: new Date().toISOString().slice(0, 10), status: "ACTIVE" });
const pretty = (value: string) => value.replaceAll("_", " ");
export default function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [page, setPage] = useState(1); const [pageCount, setPageCount] = useState(1); const [total, setTotal] = useState(0); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [sort, setSort] = useState("name"); const [loading, setLoading] = useState(true); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Customer | null>(null); const [form, setForm] = useState<Form>(blank()); const [selected, setSelected] = useState<Customer | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const p = new URLSearchParams({ page: String(page), pageSize: "10", sort }); if (search.trim()) p.set("search", search.trim()); if (status !== "ALL") p.set("status", status); const r = await fetch(`/api/owner/customer?${p}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok || !d.success) throw new Error(d.message); setCustomers(d.data); setTotal(d.meta.total); setPageCount(d.meta.pageCount); } catch (e) { toast.error(e instanceof Error ? e.message : "Failed to load customers."); } finally { setLoading(false); } }, [page, search, sort, status]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);
  function edit(c: Customer) { setEditing(c); setSelected(null); setForm({ name: c.name, phone: c.phone, email: c.email || "", profileImage: c.profileImage || "", dateOfBirth: c.dateOfBirth?.slice(0, 10) || "", gender: c.gender || "", address: c.address || "", city: c.city || "", notes: c.notes || "", registrationDate: c.registrationDate.slice(0, 10), status: c.status }); setFormOpen(true); }
  async function save() { setBusy(true); try { const r = await fetch(editing ? `/api/owner/customer/${editing.id}` : "/api/owner/customer", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok || !d.success) throw new Error(d.message); toast.success(d.message); setFormOpen(false); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : "Failed to save customer."); } finally { setBusy(false); } }
  async function details(c: Customer) { const r = await fetch(`/api/owner/customer/${c.id}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) return toast.error(d.message); setSelected(d.data); }
  async function remove(c: Customer) { if (!confirm(`Delete ${c.name}?`)) return; const r = await fetch(`/api/owner/customer/${c.id}`, { method: "DELETE" }); const d = await r.json(); if (!r.ok) return toast.error(d.message); toast.success(d.message); setSelected(null); await load(); }
  function exportCsv() { const csv = ["Customer ID,Name,Phone,Email,Status,Orders,Reservations,Spending", ...customers.map(c => [c.customerCode, c.name, c.phone, c.email || "", c.status, c.stats.totalOrders, c.stats.totalReservations, c.stats.totalSpending.toFixed(2)].map(v => `"${String(v).replaceAll('"', '""')}"`).join(","))].join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = "customers.csv"; a.click(); URL.revokeObjectURL(a.href); }
  async function importCsv(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; let count = 0; for (const row of (await file.text()).split(/\r?\n/).slice(1).filter(Boolean)) { const v = row.split(",").map(x => x.replace(/^"|"$/g, "")); if (!v[1] || !v[2]) continue; const r = await fetch("/api/owner/customer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: v[1], phone: v[2], email: v[3] || null }) }); if (r.ok) count++; } e.target.value = ""; toast.success(`${count} customer${count === 1 ? "" : "s"} imported.`); await load(); }
  async function image(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (file.size > 2 * 1024 * 1024) return toast.error("Profile image must be 2 MB or smaller."); const reader = new FileReader(); reader.onload = () => setForm({ ...form, profileImage: String(reader.result) }); reader.readAsDataURL(file); }
  return <div className="erp-page erp-page-customers space-y-6 p-6"><Toaster position="top-right" /><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Customers</h1><p className="text-muted-foreground">Manage customer profiles, history, and lifetime value</p></div><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><Download className="h-4 w-4" /> Export</button><label className="flex cursor-pointer items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><FileUp className="h-4 w-4" /> Import<input type="file" accept=".csv" onChange={importCsv} className="hidden" /></label><button onClick={() => { setEditing(null); setForm(blank()); setFormOpen(true); }} className="flex items-center gap-2 rounded-lg bg-black px-4 py-2 text-sm text-white"><Plus className="h-4 w-4" /> Add Customer</button></div></div>
  <div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search customer ID, name, phone, or email..." className="w-full rounded-xl border py-3 pl-10 pr-4" /></div><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }} className="rounded-xl border bg-white px-4 py-3"><option value="ALL">All statuses</option>{statuses.map(s => <option key={s}>{pretty(s)}</option>)}</select><select value={sort} onChange={e => setSort(e.target.value)} className="rounded-xl border bg-white px-4 py-3"><option value="name">Name</option><option value="recent">Recently registered</option></select></div>
  <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[900px] text-sm"><thead className="bg-gray-50"><tr>{["Customer", "Contact", "Activity", "Spending", "Status", "Action"].map(h => <th key={h} className="p-4 text-left font-semibold">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={6} className="p-12 text-center text-gray-500"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin" />Loading customers...</td></tr> : customers.length === 0 ? <tr><td colSpan={6} className="p-12 text-center text-gray-500">No customers found.</td></tr> : customers.map(c => <tr key={c.id} onClick={() => details(c)} className="cursor-pointer border-t hover:bg-gray-50"><td className="p-4"><p className="font-semibold">{c.name}</p><p className="text-xs text-gray-500">{c.customerCode}</p></td><td className="p-4"><p>{c.phone}</p><p className="text-xs text-gray-500">{c.email || "No email"}</p></td><td className="p-4">{c.stats.totalOrders} orders · {c.stats.totalReservations} reservations</td><td className="p-4">{c.stats.totalSpending.toFixed(2)}</td><td className="p-4"><span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-semibold">{pretty(c.status)}</span></td><td className="p-4 text-right"><Eye className="h-4 w-4 text-gray-500" /></td></tr>)}</tbody></table></div><div className="flex items-center justify-between text-sm text-gray-500"><span>{total} customer{total === 1 ? "" : "s"}</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><span>Page {page} of {pageCount}</span><button disabled={page >= pageCount} onClick={() => setPage(page + 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></div>
  {formOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-2xl font-bold">{editing ? "Edit Customer" : "Add Customer"}</h2><button onClick={() => setFormOpen(false)}><X /></button></div><div className="grid gap-3 md:grid-cols-3">{["name", "phone", "email", "city", "address"].map(key => <input key={key} placeholder={pretty(key)} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="rounded-lg border p-3" />)}<input type="date" value={form.dateOfBirth} onChange={e => setForm({ ...form, dateOfBirth: e.target.value })} className="rounded-lg border p-3" /><select value={form.gender} onChange={e => setForm({ ...form, gender: e.target.value })} className="rounded-lg border bg-white p-3"><option value="">Gender</option>{["MALE", "FEMALE", "OTHER"].map(x => <option key={x}>{pretty(x)}</option>)}</select><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className="rounded-lg border bg-white p-3">{statuses.map(x => <option key={x}>{pretty(x)}</option>)}</select><label className="rounded-lg border p-3 text-sm">Profile image<input type="file" accept="image/*" onChange={image} className="mt-1 block w-full text-xs" /></label><textarea placeholder="Notes" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} className="min-h-20 rounded-lg border p-3 md:col-span-3" /></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setFormOpen(false)} className="rounded-lg border px-5 py-2">Cancel</button><button disabled={busy} onClick={save} className="rounded-lg bg-black px-5 py-2 text-white">{busy ? "Saving..." : "Save customer"}</button></div></div></div>}
  {selected && <div className="fixed inset-0 z-50 flex justify-end bg-black/50"><div className="h-full w-full max-w-md overflow-y-auto bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-sm text-gray-500">{selected.customerCode}</p></div><button onClick={() => setSelected(null)}><X /></button></div>{selected.profileImage && <img src={selected.profileImage} alt="" className="mt-4 h-20 w-20 rounded-full object-cover" />}<div className="mt-5 space-y-2 rounded-xl bg-gray-50 p-4 text-sm"><p><b>Phone:</b> {selected.phone}</p><p><b>Email:</b> {selected.email || "—"}</p><p><b>Status:</b> {pretty(selected.status)}</p><p><b>Orders:</b> {selected.stats.totalOrders}</p><p><b>Reservations:</b> {selected.stats.totalReservations}</p><p><b>Total spending:</b> {selected.stats.totalSpending.toFixed(2)}</p><p><b>Average order:</b> {selected.stats.averageOrderValue.toFixed(2)}</p><p><b>Last visit:</b> {selected.stats.lastVisit ? new Date(selected.stats.lastVisit).toLocaleDateString() : "—"}</p><p><b>Favourite item:</b> {selected.stats.favouriteItem || "—"}</p><p><b>Favourite category:</b> {selected.stats.favouriteCategory || "—"}</p><p><b>Notes:</b> {selected.notes || "—"}</p></div><div className="mt-6 flex gap-2"><button onClick={() => edit(selected)} className="flex-1 rounded-lg border py-2"><Pencil className="mx-auto h-4 w-4" /></button><button onClick={() => remove(selected)} className="flex-1 rounded-lg border border-red-200 py-2 text-red-600"><Trash2 className="mx-auto h-4 w-4" /></button></div></div></div>}</div>;
}
